[package]
name = "rusty-chain"
version = "0.1.0"
authors = ["Don Smith <don@antiantonym.com>"]

[dependencies]
bincode = "1.0.0"
rust-crypto = "^0.2"
serde = "1.0.43"
serde_derive = "1.0.43"
time = "*"
